# Generated by Django 5.1.4 on 2025-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.TextField()),
            ],
        ),
    ]
