# Generated by Django 5.1.4 on 2025-03-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
    ]
